<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ubuntu" name="com.rc.wefunit.testengine.TestEngineTest" tests="8" failures="0" timestamp="22 May 2015 13:59:15 GMT" time="0.549" errors="1">
  <testcase name="method_getTestScores_returned_map_must_contain_report_document" time="0.000" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="method_getTestScores_returned_map_must_contain_score_document" time="0.000" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="method_executeTests_tests_reports_failed_tests_arrays_size_should_be_equal_to_total_failed_tests" time="0.317" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="method_executeTests_total_passed_tests_should_be_equal_to_total_tests_minus_total_failed_tests" time="0.044" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="method_getTestScores_returned_map_validating_failed_test_objects_structures_inside_report_failed_array" time="0.001" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="method_getTestScores_validating_the_test_classes_names_inside_report_section_of_test_scoring_map" time="0.083" classname="com.rc.wefunit.testengine.TestEngineTest">
    <error type="java.lang.AssertionError" message="expected [9] but found [22]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [22]
	at com.rc.wefunit.testengine.TestEngineTest.method_getTestScores_validating_the_test_classes_names_inside_report_section_of_test_scoring_map(TestEngineTest.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- method_getTestScores_validating_the_test_classes_names_inside_report_section_of_test_scoring_map -->
  <testcase name="method_executeTests_total_executed_tests_should_equal_to_total_no_of_tests_present" time="0.056" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="method_executeTests_total_test_for_explicitly_failed_tests" time="0.048" classname="com.rc.wefunit.testengine.TestEngineTest"/>
</testsuite> <!-- com.rc.wefunit.testengine.TestEngineTest -->
